#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hyshin <kirikeria@gmail.com>               +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/24 11:19:38 by hyshin            #+#    #+#              #
#    Updated: 2019/10/18 16:44:13 by hyshin           ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = ft_display_file

OBJS = main.o

SOURCE = main.c

ALL:$(NAME)

$(NAME):
	gcc -Wall -Wextra -Werror -o $(NAME) $(SOURCE)

clean:
	/bin/rm -f $(OBJS)

fclean:
	/bin/rm -f $(NAME)